trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
- repo: self

variables:
- group: press
  
- name: StartupProject
  value: Press.Worker

- name: DockerFile
  value: ./_infra/press.worker/Dockerfile
  
- name: ContainerImage
  value: $(Worker.Image):$(Build.BuildNumber)
    
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
      - bash: |
          echo '$(Docker.PAT)' | docker login -u $(Docker.User) --password-stdin $(Docker.Registry)

          docker buildx create --use

          docker buildx build \
            -t $(Docker.Registry)/$(ContainerImage) \
            --build-arg StartupProject=$(StartupProject) \
            --platform linux/arm64,linux/amd64 \
            -f $(DockerFile) \
            --push \
            .
        displayName: Build & Publish Image
          
- stage: Deploy
  dependsOn: Build
  jobs:
    - job: Captain
      steps:
      - bash: |
          sudo npm install -g caprover
          caprover deploy -u $(Worker.Captain.Server) -p $(Worker.Captain.Password) -a $(Worker.Captain.App) -i $(ContainerImage)
        displayName: Deploy to Captain