trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
- repo: self

variables:
- group: press
  
- name: StartupProject
  value: Press.Web
  
- name: ContainerImage
  value: $(Web.Image)
  
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
      - bash: |
          docker build -t $(ContainerImage) \
            --build-arg StartupProject=$(StartupProject) \
            -f ./_infra/press.web/Dockerfile \
            .
        displayName: Build Image

      - task: Docker@2
        displayName: Publish Image
        inputs:
          command: push
          repository: $(ContainerImage)
          containerRegistry: 'Docker Hub'
          dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          tags: 'latest'
          
- stage: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: $(Web.Azure.Subscription)
        appName: $(Web.Azure.App)
        containers: $(ContainerImage)
