trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
- repo: self

variables:
- group: press
  
- name: StartupProject
  value: Press.Web

- name: DockerFile
  value: ./_infra/press.web/Dockerfile
  
- name: ContainerImage
  value: $(Web.Image):$(Build.BuildNumber)
  
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
      - bash: |
          echo '$(Docker.PAT)' | docker login -u $(Docker.User) --password-stdin $(Docker.Registry)

          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

          docker buildx create --use

          docker buildx build \
            -t $(Docker.Registry)/$(ContainerImage) \
            --build-arg StartupProject=$(StartupProject) \
            --platform linux/arm64,linux/amd64 \
            -f $(DockerFile) \
            --push \
            .
        displayName: Build & Publish Image
          
- stage: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: $(Web.Azure.Subscription)
        appName: $(Web.Azure.App)
        containers: $(ContainerImage)
